apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: three-tier
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # GCP default StorageClass
  gcePersistentDisk:
    pdName: mongo-disk        # name of the GCP Persistent Disk
    fsType: ext4
