apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  # added for GCP LB
spec: 
  ports:
  - port: 3500
    protocol: TCP
  type: ClusterIP
  selector:
    role: api