apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      imagePullSecrets:
      - name: gcp-registry-secret   # updated for GCP Artifact Registry
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/fair-plasma-441014-q1/frontend-repo/frontend@sha256:1852c1f1e0b3f85bfe2163371293b26579405b9f9171fd9c86afe1e687e473a7
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://codeworld.gdn/api/tasks"
        ports:
        - containerPort: 3000
