apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    targetPort: 3000   # good practice to explicitly map
    protocol: TCP
  selector:
    role: frontend
  type: ClusterIP

